#pragma once

enum EPacketType : WORD
{
	PACKET_TYPE_CS_CHAT_SERVER = 0,
	PACKET_TYPE_CS_CHAT_REQ_LOGIN,
	PACKET_TYPE_SC_CHAT_RES_LOGIN,
	PACKET_TYPE_CS_CHAT_REQ_SECTOR_MOVE,
	PACKET_TYPE_SC_CHAT_RES_SECTOR_MOVE,
	PACKET_TYPE_CS_CHAT_REQ_MESSAGE,
	PACKET_TYPE_SC_CHAT_RES_MESSAGE,
	PACKET_TYPE_CS_CHAT_REQ_HEARTBEAT
};